areas:
  finish:
  - - 0
    - 972
    - 1920
    - 107
  start:
  - - 0
    - 0
    - 1920
    - 108
  vision:
  - - 0
    - 0
    - 1920
    - 1080
params:
- caption: Webcam exposure Level
  default: 8
  key: exposure
  max: 10
  min: 0
- caption: YOLO Confidence Level (%)
  default: 40
  key: yolo_confidence
  max: 100
  min: 0
  type: *id001
- caption: Bytetrack Confidence Level (%)
  default: 40
  key: bytetrack_confidence
  max: 100
  min: 0
  type: *id001
- caption: ByteTrack frame memory
  default: 30
  key: tracking_memory
  max: 60
  min: 1
  type: *id001
- caption: Movement threshold (pixels)
  default: 15
  key: pixel_tolerance
  max: 50
  min: 2
  type: *id001
- caption: Histogram normalization
  default: 0
  key: img_normalization
  max: 1
  min: 0
  type: *id001
- caption: Brightness adjustment
  default: 0
  key: img_brightness
  max: 1
  min: 0
  type: *id001
reference_frame:
- 0
- 0
