name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10  # Use Python 3.10 or higher

    # Install Poetry
    - name: Install Poetry
      run: |
        python -m pip install --upgrade pip
        pip install poetry

    # Install dependencies
    - name: Install dependencies
      run: poetry install

    # Run tests
    - name: Run tests
      run: poetry run pytest